export enum ProductCategory {
  ULTRASSONOGRAFIA = 'Ultrassonografia',
  ECG = 'Eletrocardiograma (ECG)',
  APARELHO_RAIOX = 'Aparelho de Raio-X',
  ESTETOSCOPIO = 'Estetoscópio',
  MONITOR_PRESSAO = 'Monitor de Pressão Arterial',
  OXIMETRO_PULSO = 'Oxímetro de Pulso',
  CENTRIFUGA = 'Centrífuga',
  MICROSCOPIO = 'Microscópio',
  ANALISADOR_SANGUE = 'Analisador de Sangue',
  MANEQUINS_SIMULACAO = 'Manequins de Simulação',
  SIMULADOR_REALIDADE_VIRTUAL = 'Simulador de Realidade Virtual',
  INSTRUMENTOS_CIRURGICOS = 'Instrumentos Cirúrgicos',
  SISTEMA_LAPAROSCOPIA = 'Sistema de Laparoscopia',
  DESFIBRILADOR = 'Desfibrilador',
  BOMBA_INFUSAO = 'Bomba de Infusão',
  AUTOCLAVE = 'Autoclave',
  ESTERILIZADOR_UV = 'Esterilizador UV',
  MAQUINA_FISIOTERAPIA = 'Máquina de Fisioterapia',
  RESPIRADOR = 'Respirador',
}
