export enum ProductCategory {
  ESTETOSCOPIO = 'ESTETOSCOPIO',
  MONITOR_PRESSAO = 'MONITOR_PRESSAO',
  OXIMETRO_PULSO = 'OXIMETRO_PULSO',
  MICROSCOPIO = 'MICROSCOPIO',
  MANEQUINS_SIMULACAO = 'MANEQUINS_SIMULACAO',
  INSTRUMENTOS_CIRURGICOS = 'INSTRUMENTOS_CIRURGICOS',
  DESFIBRILADOR = 'DESFIBRILADOR',
  BOMBA_INFUSAO = 'BOMBA_INFUSAO',
  RESPIRADOR = 'RESPIRADOR',
}
